using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Test
{
    public class GameData
    {
        public float //MaxHealth,
                     //HealthRegen,
                     //MaxStamina,
             StaminaRegen,
             //StaminaCostReduction,
             //MaxMana,
             //ManaRegen,
             //Impact,
             //AllDamages,
             //PhysicalDamage,
             //EtherealDamage,
             //DecayDamage,
             //ElectricDamage,
             //FrostDamage,
             //FireDamage,
             //DarkDamage,
             //LightDamage,
             //DamageProtection,
             //PhysicalProtection,
             //EtherealProtection,
             //DecayProtection,
             //ElectricProtection,
             //FrostProtection,
             //FireProtection,
             //DarkProtection,
             //LightProtection,
             //AllResistances,
             //DamageResistance,
             //PhysicalResistance,
             //EtherealResistance,
             //DecayResistance,
             //ElectricResistance,
             //FrostResistance,
             //FireResistance,
             //DarkResistance,
             //LightResistance,
             //ImpactResistance,
             //StabilityRegen,
             //EnvColdProtection,
             //EnvHeatProtection,
             //ColdRegen,
             //HeatRegen,
             //Waterproof,
             //CorruptionProtection,
             //TemperatureModifier,
             MovementSpeed;
        //Speed,
        //AttackSpeed,
        //MaxFood,
        //FoodDepleteRate,
        //MaxDrink,
        //DrinkDepleteRate,
        //MaxSleep,
        //SleepDepleteRate,
        //Detectability,
        //VisualDetectability,
        //PouchCapacity,
        //FoodEffectEfficiency,
        //SummonLifeSPan;
    }
}
